# This is a basic workflow to help you get started with Actions

name: GitHub Metrics Image

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 */7 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Config shared across all metrics image generations
  template: classic
  config_display: large
  config_timezone: Asia/Singapore

jobs:
  metrics-base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: ${{ env.template }}
          config_display: ${{ env.config_display }}
          config_timezone: ${{ env.config_timezone }}
          token: ${{ secrets.METRICS_TOKEN }}
          user: tasercake
          filename: metrics/base.svg
          base: activity, repositories, community
  metrics-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: ${{ env.template }}
          config_display: ${{ env.config_display }}
          config_timezone: ${{ env.config_timezone }}
          token: ${{ secrets.METRICS_TOKEN }}
          user: tasercake
          filename: metrics/languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: jupyter notebook, AMPL, SCSS, HTML
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
  metrics-achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: ${{ env.template }}
          config_display: ${{ env.config_display }}
          config_timezone: ${{ env.config_timezone }}
          token: ${{ secrets.METRICS_TOKEN }}
          user: tasercake
          filename: metrics/achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
  metrics-habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: ${{ env.template }}
          config_display: ${{ env.config_display }}
          config_timezone: ${{ env.config_timezone }}
          token: ${{ secrets.METRICS_TOKEN }}
          user: tasercake
          filename: metrics/habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
  metrics-stars:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: ${{ env.template }}
          config_display: ${{ env.config_display }}
          config_timezone: ${{ env.config_timezone }}
          token: ${{ secrets.METRICS_TOKEN }}
          user: tasercake
          filename: metrics/stars.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 6
