# Update README.md with a list of my recent blog posts
name: Recent Blog Posts

# Controls when the workflow will run
on:
  schedule:
    # Every day
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  recent-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in hashnode.dev posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.penukonda.me/rss.xml"
